//! Stable wire message type identifiers.
//!
//! `MessageType` is part of the public XACE engine-adapter contract. The
//! numeric discriminants are frozen for protocol v1 and must never be reused
//! for a different semantic meaning. JSON serialization intentionally keeps
//! Rust/serde variant names for readability; the `as_u8` value is the compact
//! transport discriminator used by low-level adapters and metrics.

use serde::{Deserialize, Serialize};

/// The direction a message is allowed to travel.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum MessageDirection {
    /// Runtime/server to engine adapter/client.
    XaceToEngine,
    /// Engine adapter/client to runtime/server.
    EngineToXace,
    /// Valid in both directions.
    Bidirectional,
}

impl MessageDirection {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::XaceToEngine => "xace_to_engine",
            Self::EngineToXace => "engine_to_xace",
            Self::Bidirectional => "bidirectional",
        }
    }
}

impl std::fmt::Display for MessageDirection {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// The stable type of a `WireMessage`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[repr(u8)]
pub enum MessageType {
    /// Complete visual/world reconstruction payload.
    Snapshot = 0,
    /// Incremental authoritative state changes.
    Delta = 1,
    /// Input generated by the engine adapter.
    Input = 2,
    /// Runtime event notification for the engine adapter.
    Event = 3,
    /// Handshake, ping, reconnect, snapshot request, and lifecycle control.
    Control = 4,
    /// Engine-side results and observations.
    Feedback = 5,
}

impl MessageType {
    /// All currently assigned protocol-v1 message types in discriminant order.
    pub const ALL: [MessageType; 6] = [
        MessageType::Snapshot,
        MessageType::Delta,
        MessageType::Input,
        MessageType::Event,
        MessageType::Control,
        MessageType::Feedback,
    ];

    pub const MIN_DISCRIMINANT: u8 = MessageType::Snapshot as u8;
    pub const MAX_DISCRIMINANT: u8 = MessageType::Feedback as u8;

    /// Returns the stable compact wire discriminant.
    pub fn as_u8(self) -> u8 {
        self as u8
    }

    /// Constructs a message type from its compact wire discriminant.
    pub fn from_u8(value: u8) -> Option<Self> {
        match value {
            0 => Some(Self::Snapshot),
            1 => Some(Self::Delta),
            2 => Some(Self::Input),
            3 => Some(Self::Event),
            4 => Some(Self::Control),
            5 => Some(Self::Feedback),
            _ => None,
        }
    }

    /// Parses a protocol name. Accepts canonical names plus common separators.
    pub fn from_name(value: &str) -> Option<Self> {
        let normalized = value.trim().replace(['-', ' '], "_").to_ascii_lowercase();
        match normalized.as_str() {
            "snapshot" => Some(Self::Snapshot),
            "delta" => Some(Self::Delta),
            "input" => Some(Self::Input),
            "event" => Some(Self::Event),
            "control" => Some(Self::Control),
            "feedback" | "feed_back" => Some(Self::Feedback),
            _ => None,
        }
    }

    /// Canonical uppercase protocol name.
    pub fn name(self) -> &'static str {
        match self {
            Self::Snapshot => "SNAPSHOT",
            Self::Delta => "DELTA",
            Self::Input => "INPUT",
            Self::Event => "EVENT",
            Self::Control => "CONTROL",
            Self::Feedback => "FEEDBACK",
        }
    }

    /// Human-readable payload contract for diagnostics.
    pub fn payload_kind(self) -> &'static str {
        match self {
            Self::Snapshot => "SnapshotPayload",
            Self::Delta => "DeltaPayload",
            Self::Input => "InputPayload",
            Self::Event => "EventPayload",
            Self::Control => "ControlPayload",
            Self::Feedback => "FeedbackPayload",
        }
    }

    pub fn direction(self) -> MessageDirection {
        match self {
            Self::Snapshot | Self::Delta | Self::Event => MessageDirection::XaceToEngine,
            Self::Input | Self::Feedback => MessageDirection::EngineToXace,
            Self::Control => MessageDirection::Bidirectional,
        }
    }

    pub fn is_xace_to_engine(self) -> bool {
        matches!(self.direction(), MessageDirection::XaceToEngine)
    }

    pub fn is_engine_to_xace(self) -> bool {
        matches!(self.direction(), MessageDirection::EngineToXace)
    }

    pub fn is_bidirectional(self) -> bool {
        matches!(self.direction(), MessageDirection::Bidirectional)
    }

    /// Returns true when this message type is legal in the supplied direction.
    pub fn can_flow(self, direction: MessageDirection) -> bool {
        self.direction() == direction || self.is_bidirectional()
    }

    pub fn is_state_replacement(self) -> bool {
        matches!(self, Self::Snapshot)
    }

    pub fn is_state_delta(self) -> bool {
        matches!(self, Self::Delta)
    }
}

impl std::fmt::Display for MessageType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.name())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn discriminants_are_unique_and_contiguous() {
        let mut seen = HashSet::new();
        for (idx, ty) in MessageType::ALL.iter().copied().enumerate() {
            assert_eq!(ty.as_u8(), idx as u8);
            assert!(seen.insert(ty.as_u8()));
            assert_eq!(MessageType::from_u8(ty.as_u8()), Some(ty));
        }
        assert_eq!(MessageType::MIN_DISCRIMINANT, 0);
        assert_eq!(MessageType::MAX_DISCRIMINANT, 5);
        assert!(MessageType::from_u8(6).is_none());
        assert!(MessageType::from_u8(u8::MAX).is_none());
    }

    #[test]
    fn names_parse_case_and_separators() {
        assert_eq!(
            MessageType::from_name("SNAPSHOT"),
            Some(MessageType::Snapshot)
        );
        assert_eq!(MessageType::from_name("input"), Some(MessageType::Input));
        assert_eq!(
            MessageType::from_name(" feed-back "),
            Some(MessageType::Feedback)
        );
        assert_eq!(MessageType::from_name("not-a-message"), None);
    }

    #[test]
    fn directions_match_contract() {
        assert!(MessageType::Snapshot.is_xace_to_engine());
        assert!(MessageType::Delta.is_xace_to_engine());
        assert!(MessageType::Event.is_xace_to_engine());
        assert!(MessageType::Input.is_engine_to_xace());
        assert!(MessageType::Feedback.is_engine_to_xace());
        assert!(MessageType::Control.is_bidirectional());

        assert!(MessageType::Control.can_flow(MessageDirection::XaceToEngine));
        assert!(MessageType::Control.can_flow(MessageDirection::EngineToXace));
        assert!(!MessageType::Delta.can_flow(MessageDirection::EngineToXace));
    }

    #[test]
    fn display_and_payload_kind_are_stable() {
        assert_eq!(MessageType::Snapshot.to_string(), "SNAPSHOT");
        assert_eq!(MessageType::Feedback.payload_kind(), "FeedbackPayload");
        assert_eq!(MessageDirection::Bidirectional.to_string(), "bidirectional");
    }
}
