"""Typed prompt-to-CGS operation contract.

This package is intentionally independent from the legacy path/value
``MutationOp`` model.  Provider output is parsed into the closed operation
vocabulary here before any CGS path or JSON fragment is constructed.
"""

from .operation_model import (
    TYPED_OPERATION_BATCH_SCHEMA,
    AddAssetOperation,
    AddComponentOperation,
    AddEventOperation,
    AddGeneratedSystemOperation,
    AddRuleOperation,
    AddSystemOperation,
    AssetStatus,
    AssetType,
    ComponentField,
    DeclareComponentOperation,
    DefaultAssignment,
    EventPayloadField,
    FieldType,
    GeneratedSystemBehaviorKind,
    IncrementNumericFieldBehavior,
    OperationKind,
    SetDefaultsOperation,
    SystemPhase,
    SystemScope,
    TypedCgsOperation,
    TypedCgsOperationBatch,
    TypedOperationError,
)
from .operation_registry import (
    OPERATION_REGISTRY,
    TypedCgsFragmentPlan,
    compile_typed_operation_batch,
    normalized_typed_operation_batch,
    parse_typed_operation_batch,
    serialize_typed_operation_batch,
    typed_operation_batch_json_schema,
)
from .cgs_adapter import (
    BUILTIN_COMPONENT_NAMES,
    BUILTIN_SYSTEM_CONTRACTS,
    TypedCgsApplyResult,
    TypedOperationValidationResult,
    apply_typed_operation_batch,
    validate_typed_operation_batch,
)
from .composite_plan import (
    COMPOSITE_PROMPT_PLAN_SCHEMA,
    COMPOSITE_REQUIRED_FACETS,
    NETWORK_COMPONENT_TYPE_IDS,
    SAVE_COMPONENT_TYPE_IDS,
    CompositePromptPlan,
    CompositePromptPlanValidation,
    build_composite_prompt_plan,
    composite_plan_has_required_facets,
    validate_composite_prompt_plan,
)

__all__ = [
    "AddAssetOperation",
    "AddComponentOperation",
    "AddEventOperation",
    "AddGeneratedSystemOperation",
    "AddRuleOperation",
    "AddSystemOperation",
    "AssetStatus",
    "AssetType",
    "BUILTIN_COMPONENT_NAMES",
    "BUILTIN_SYSTEM_CONTRACTS",
    "COMPOSITE_PROMPT_PLAN_SCHEMA",
    "COMPOSITE_REQUIRED_FACETS",
    "ComponentField",
    "CompositePromptPlan",
    "CompositePromptPlanValidation",
    "DeclareComponentOperation",
    "DefaultAssignment",
    "EventPayloadField",
    "FieldType",
    "GeneratedSystemBehaviorKind",
    "IncrementNumericFieldBehavior",
    "NETWORK_COMPONENT_TYPE_IDS",
    "OPERATION_REGISTRY",
    "OperationKind",
    "SAVE_COMPONENT_TYPE_IDS",
    "SetDefaultsOperation",
    "SystemPhase",
    "SystemScope",
    "TYPED_OPERATION_BATCH_SCHEMA",
    "TypedCgsFragmentPlan",
    "TypedCgsApplyResult",
    "TypedCgsOperation",
    "TypedCgsOperationBatch",
    "TypedOperationError",
    "TypedOperationValidationResult",
    "apply_typed_operation_batch",
    "build_composite_prompt_plan",
    "compile_typed_operation_batch",
    "composite_plan_has_required_facets",
    "normalized_typed_operation_batch",
    "parse_typed_operation_batch",
    "serialize_typed_operation_batch",
    "typed_operation_batch_json_schema",
    "validate_composite_prompt_plan",
    "validate_typed_operation_batch",
]
