//! # System Definition
//!
//! Defines a game system in the CGS. A SystemDefinition is the schema
//! declaration of a system — what it reads, what it writes, which phase
//! it runs in, and whether it is deterministic.
//!
//! ## What a System Is
//! A system is a unit of game logic that runs every tick. It reads
//! component data, computes results, and submits mutations via the
//! Mutation Gate. Systems never call each other directly — they
//! communicate only through components and events (I4).
//!
//! ## Schema vs Implementation
//! SystemDefinition lives in the CGS — it is the contract.
//! The actual Rust implementation of the system is generated by the
//! Code Generation Engine (Phase 13, PIL submodule 13) and compiled
//! into the runtime. The SGC uses SystemDefinition to build the
//! ExecutionPlan — it never touches the implementation.
//!
//! ## Read/Write Declarations
//! Every system must explicitly declare which component type IDs it
//! reads and which it writes. The SGC uses these declarations to:
//! - Detect read-after-write hazards (D1)
//! - Build parallel execution groups
//! - Validate no undeclared writes occur (enforced by SystemContext)
//!
//! ## Determinism Flag
//! Systems marked deterministic=true are held to strict D-rule enforcement
//! by the DeterminismGuard. Systems marked false are flagged as warnings
//! during SGC compilation — all systems in XACE should be deterministic.

use serde::{Deserialize, Serialize};

/// Component type ID for system read/write declarations.
/// Maps to registered component type IDs in CompositeComponentRegistry.
pub type ComponentTypeId = u32;

/// Unique identifier for a system within the CGS.
pub type SystemId = String;

// ── Execution Phase ───────────────────────────────────────────────────────────

/// The execution phase in which a system runs each tick.
///
/// Phases are fixed and immutable — defined by PhaseEnum in runtime/phase_enum.rs.
/// The SGC validates that every system is assigned to exactly one phase.
/// Systems in the same phase may run in parallel if their read/write
/// declarations are conflict-free (determined by SGC conflict analyzer).
///
/// ## Phase Order (fixed, immutable)
/// Initialization → Input → Simulation → PostSimulation → Cleanup
///
/// This enum mirrors PhaseEnum in the runtime — kept in sync manually.
/// The wire protocol uses the discriminant value (u8) for serialization.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
pub enum ExecutionPhase {
    /// World setup, entity spawning, initial state configuration.
    /// Runs once at world load, then only when new entities are spawned.
    Initialization = 0,

    /// Input collection and routing. Applies player and network input.
    /// All input must be applied here — never in Simulation (D12).
    Input = 1,

    /// Core game logic — movement, AI, combat, physics, abilities.
    /// The main gameplay phase. Most systems run here.
    Simulation = 2,

    /// Post-processing — camera follow, UI updates, animation state.
    /// Reads final Simulation state. Writes are limited to cosmetic data.
    PostSimulation = 3,

    /// Cleanup — remove consumed events, destroy requested entities,
    /// clear temporary state, advance lifetime counters.
    Cleanup = 4,
}

impl ExecutionPhase {
    /// Returns the u8 discriminant value for wire serialization.
    pub fn as_u8(&self) -> u8 {
        match self {
            ExecutionPhase::Initialization => 0,
            ExecutionPhase::Input => 1,
            ExecutionPhase::Simulation => 2,
            ExecutionPhase::PostSimulation => 3,
            ExecutionPhase::Cleanup => 4,
        }
    }

    /// Constructs an ExecutionPhase from its u8 discriminant.
    /// Returns None if the value is not a valid phase.
    pub fn from_u8(value: u8) -> Option<Self> {
        match value {
            0 => Some(ExecutionPhase::Initialization),
            1 => Some(ExecutionPhase::Input),
            2 => Some(ExecutionPhase::Simulation),
            3 => Some(ExecutionPhase::PostSimulation),
            4 => Some(ExecutionPhase::Cleanup),
            _ => None,
        }
    }

    /// Returns true if this phase allows writing to gameplay components.
    /// PostSimulation and Cleanup have restricted write access.
    pub fn allows_gameplay_writes(&self) -> bool {
        matches!(
            self,
            ExecutionPhase::Initialization
                | ExecutionPhase::Input
                | ExecutionPhase::Simulation
        )
    }
}

impl std::fmt::Display for ExecutionPhase {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ExecutionPhase::Initialization => write!(f, "Initialization"),
            ExecutionPhase::Input => write!(f, "Input"),
            ExecutionPhase::Simulation => write!(f, "Simulation"),
            ExecutionPhase::PostSimulation => write!(f, "PostSimulation"),
            ExecutionPhase::Cleanup => write!(f, "Cleanup"),
        }
    }
}

// ── System Version ────────────────────────────────────────────────────────────

/// Version of a system implementation.
///
/// Incremented when the system's behavior changes in a way that
/// affects determinism or snapshot compatibility.
/// The SGC embeds system versions in the ExecutionPlan.
/// Runtime halts if system version mismatches ExecutionPlan (I7).
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct SystemVersion {
    pub major: u32,
    pub minor: u32,
}

impl SystemVersion {
    pub const INITIAL: SystemVersion = SystemVersion { major: 1, minor: 0 };

    pub fn new(major: u32, minor: u32) -> Self {
        Self { major, minor }
    }
}

impl Default for SystemVersion {
    fn default() -> Self {
        SystemVersion::INITIAL
    }
}

impl std::fmt::Display for SystemVersion {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}.{}", self.major, self.minor)
    }
}

// ── System Definition ─────────────────────────────────────────────────────────

/// The schema declaration of a game system.
///
/// Defines what a system does, what it reads and writes, when it runs,
/// and what it depends on. The SGC reads SystemDefinitions to build
/// the dependency graph and produce a deterministic ExecutionPlan.
///
/// ## Read and Write Sets
/// `reads` and `writes` are sets of component type IDs.
/// A system that reads COMP_TRANSFORM_V1 (ID=1) and writes COMP_VELOCITY_V1
/// (ID=5) declares: reads=[1], writes=[5].
///
/// The SGC uses these to:
/// - Detect RAW hazards: system B reads what system A writes
/// - Detect WAW hazards: systems A and B both write the same component
/// - Build parallel groups: systems with no shared writes run in parallel
///
/// Undeclared reads are permitted (read-only access is safe).
/// Undeclared writes are a determinism violation — blocked by SystemContext.
///
/// ## Dependencies
/// `depends_on` declares explicit ordering constraints beyond what the
/// read/write analysis produces. Use sparingly — only when ordering
/// must be guaranteed even without a data hazard.
/// Example: AnimationSystem must run after MovementSystem even though
/// it only reads COMP_TRANSFORM_V1 (which MovementSystem also only reads).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SystemDefinition {
    /// Unique identifier for this system within the CGS.
    /// Used by SGC to build the dependency graph and ExecutionPlan.
    /// Examples: "sys_movement", "sys_ai_behavior", "sys_damage"
    pub id: SystemId,

    /// Human-readable name for builder UI and Design Mentor.
    /// Examples: "MovementSystem", "AIBehaviorSystem", "DamageSystem"
    pub display_name: String,

    /// Which phase this system runs in each tick.
    /// Validated by SGC phase segmentation layer.
    pub phase: ExecutionPhase,

    /// Component type IDs this system reads each tick.
    /// Sorted ascending for deterministic SGC graph construction (D11).
    /// May be empty for systems that read no components (rare).
    pub reads: Vec<ComponentTypeId>,

    /// Component type IDs this system writes each tick via Mutation Gate.
    /// Sorted ascending for deterministic hazard detection (D11).
    /// Systems must declare ALL components they write — no exceptions.
    pub writes: Vec<ComponentTypeId>,

    /// System IDs this system must run after, regardless of data hazards.
    /// Explicit ordering constraint. Use only when necessary.
    /// Sorted alphabetically for deterministic graph construction (D11).
    pub depends_on: Vec<SystemId>,

    /// Whether this system is deterministic across all runs.
    /// Must be true for all XACE systems — false triggers SGC warning.
    /// A system is deterministic if: same input state → same output state,
    /// always, on any machine, in any order within its parallel group.
    pub deterministic: bool,

    /// Implementation version of this system.
    /// Embedded in ExecutionPlan. Runtime validates on load (I7).
    pub version: SystemVersion,

    /// Human-readable description of what this system does.
    /// Used by Design Mentor and builder UI system browser.
    pub description: String,
}

impl SystemDefinition {
    /// Creates a minimal system definition in the Simulation phase.
    /// No reads, no writes, no dependencies — to be filled in.
    pub fn new(id: impl Into<String>, display_name: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            display_name: display_name.into(),
            phase: ExecutionPhase::Simulation,
            reads: Vec::new(),
            writes: Vec::new(),
            depends_on: Vec::new(),
            deterministic: true,
            version: SystemVersion::INITIAL,
            description: String::new(),
        }
    }

    /// Creates a system definition with full specification.
    pub fn with_spec(
        id: impl Into<String>,
        display_name: impl Into<String>,
        phase: ExecutionPhase,
        reads: Vec<ComponentTypeId>,
        writes: Vec<ComponentTypeId>,
    ) -> Self {
        let mut reads = reads;
        let mut writes = writes;
        reads.sort();
        writes.sort();

        Self {
            id: id.into(),
            display_name: display_name.into(),
            phase,
            reads,
            writes,
            depends_on: Vec::new(),
            deterministic: true,
            version: SystemVersion::INITIAL,
            description: String::new(),
        }
    }

    /// Returns true if this system reads the given component type.
    pub fn reads_component(&self, type_id: ComponentTypeId) -> bool {
        self.reads.binary_search(&type_id).is_ok()
    }

    /// Returns true if this system writes the given component type.
    pub fn writes_component(&self, type_id: ComponentTypeId) -> bool {
        self.writes.binary_search(&type_id).is_ok()
    }

    /// Returns true if this system has a read-after-write hazard with another.
    ///
    /// A RAW hazard exists when this system reads a component that the
    /// other system writes. The SGC uses this to enforce ordering:
    /// the writer must run before the reader.
    pub fn has_raw_hazard_with(&self, other: &SystemDefinition) -> bool {
        self.reads.iter().any(|r| other.writes_component(*r))
    }

    /// Returns true if this system has a write-after-write hazard with another.
    ///
    /// A WAW hazard exists when both systems write the same component.
    /// The SGC serializes WAW-hazard systems — they cannot run in parallel.
    /// Tie-breaking is by lexicographic system ID (D1).
    pub fn has_waw_hazard_with(&self, other: &SystemDefinition) -> bool {
        self.writes.iter().any(|w| other.writes_component(*w))
    }

    /// Returns true if this system explicitly depends on another by ID.
    pub fn depends_on_system(&self, system_id: &str) -> bool {
        self.depends_on.iter().any(|d| d == system_id)
    }

    /// Adds a read component type ID, maintaining sorted order (D11).
    /// No-op if already present.
    pub fn add_read(&mut self, type_id: ComponentTypeId) {
        if self.reads.binary_search(&type_id).is_err() {
            let pos = self.reads.partition_point(|&r| r < type_id);
            self.reads.insert(pos, type_id);
        }
    }

    /// Adds a write component type ID, maintaining sorted order (D11).
    /// No-op if already present.
    pub fn add_write(&mut self, type_id: ComponentTypeId) {
        if self.writes.binary_search(&type_id).is_err() {
            let pos = self.writes.partition_point(|&w| w < type_id);
            self.writes.insert(pos, type_id);
        }
    }

    /// Validates this system definition for internal consistency.
    ///
    /// Checks:
    /// - ID is not empty
    /// - Read and write sets are sorted (D11)
    /// - No component appears in both reads and writes
    ///   (a system either reads or writes a component, not both —
    ///    if it writes, the write is the authoritative access)
    /// - depends_on contains no self-references
    pub fn validate(&self) -> Result<(), String> {
        if self.id.is_empty() {
            return Err("SystemDefinition ID must not be empty".into());
        }

        // Reads must be sorted
        for window in self.reads.windows(2) {
            if window[0] >= window[1] {
                return Err(format!(
                    "System {} reads are not sorted ascending",
                    self.id
                ));
            }
        }

        // Writes must be sorted
        for window in self.writes.windows(2) {
            if window[0] >= window[1] {
                return Err(format!(
                    "System {} writes are not sorted ascending",
                    self.id
                ));
            }
        }

        // No self-dependency
        if self.depends_on.iter().any(|d| d == &self.id) {
            return Err(format!(
                "System {} cannot depend on itself",
                self.id
            ));
        }

        Ok(())
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn movement_system() -> SystemDefinition {
        SystemDefinition::with_spec(
            "sys_movement",
            "MovementSystem",
            ExecutionPhase::Simulation,
            vec![1, 6], // reads: TRANSFORM, INPUT
            vec![1, 5], // writes: TRANSFORM, VELOCITY
        )
    }

    fn ai_system() -> SystemDefinition {
        SystemDefinition::with_spec(
            "sys_ai",
            "AISystem",
            ExecutionPhase::Simulation,
            vec![1, 5], // reads: TRANSFORM, VELOCITY
            vec![5],    // writes: VELOCITY
        )
    }

    #[test]
    fn new_system_is_deterministic_by_default() {
        let sys = SystemDefinition::new("sys_test", "TestSystem");
        assert!(sys.deterministic);
    }

    #[test]
    fn new_system_is_in_simulation_phase() {
        let sys = SystemDefinition::new("sys_test", "TestSystem");
        assert_eq!(sys.phase, ExecutionPhase::Simulation);
    }

    #[test]
    fn reads_sorted_on_creation() {
        let sys = SystemDefinition::with_spec(
            "sys_test", "Test",
            ExecutionPhase::Simulation,
            vec![5, 1, 3],
            vec![],
        );
        assert_eq!(sys.reads, vec![1, 3, 5]);
    }

    #[test]
    fn writes_sorted_on_creation() {
        let sys = SystemDefinition::with_spec(
            "sys_test", "Test",
            ExecutionPhase::Simulation,
            vec![],
            vec![9, 2, 6],
        );
        assert_eq!(sys.writes, vec![2, 6, 9]);
    }

    #[test]
    fn reads_component_works() {
        let sys = movement_system();
        assert!(sys.reads_component(1));
        assert!(sys.reads_component(6));
        assert!(!sys.reads_component(99));
    }

    #[test]
    fn writes_component_works() {
        let sys = movement_system();
        assert!(sys.writes_component(1));
        assert!(sys.writes_component(5));
        assert!(!sys.writes_component(6));
    }

    #[test]
    fn raw_hazard_detected() {
        let movement = movement_system();
        let ai = ai_system();
        // AI reads VELOCITY(5), movement writes VELOCITY(5) — RAW hazard
        assert!(ai.has_raw_hazard_with(&movement));
    }

    #[test]
    fn waw_hazard_detected() {
        let movement = movement_system();
        let ai = ai_system();
        // Both write VELOCITY(5) — WAW hazard
        assert!(movement.has_waw_hazard_with(&ai));
        assert!(ai.has_waw_hazard_with(&movement));
    }

    #[test]
    fn no_hazard_between_independent_systems() {
        let sys_a = SystemDefinition::with_spec(
            "sys_a", "A",
            ExecutionPhase::Simulation,
            vec![1],
            vec![2],
        );
        let sys_b = SystemDefinition::with_spec(
            "sys_b", "B",
            ExecutionPhase::Simulation,
            vec![3],
            vec![4],
        );
        assert!(!sys_a.has_raw_hazard_with(&sys_b));
        assert!(!sys_a.has_waw_hazard_with(&sys_b));
    }

    #[test]
    fn add_read_maintains_sorted_order() {
        let mut sys = SystemDefinition::new("sys_test", "Test");
        sys.add_read(5);
        sys.add_read(1);
        sys.add_read(3);
        assert_eq!(sys.reads, vec![1, 3, 5]);
    }

    #[test]
    fn add_read_no_duplicates() {
        let mut sys = SystemDefinition::new("sys_test", "Test");
        sys.add_read(1);
        sys.add_read(1);
        assert_eq!(sys.reads.len(), 1);
    }

    #[test]
    fn add_write_maintains_sorted_order() {
        let mut sys = SystemDefinition::new("sys_test", "Test");
        sys.add_write(9);
        sys.add_write(2);
        sys.add_write(6);
        assert_eq!(sys.writes, vec![2, 6, 9]);
    }

    #[test]
    fn validate_passes_for_valid_system() {
        assert!(movement_system().validate().is_ok());
    }

    #[test]
    fn validate_fails_for_empty_id() {
        let sys = SystemDefinition::new("", "Test");
        assert!(sys.validate().is_err());
    }

    #[test]
    fn validate_fails_for_self_dependency() {
        let mut sys = SystemDefinition::new("sys_test", "Test");
        sys.depends_on.push("sys_test".into());
        assert!(sys.validate().is_err());
    }

    #[test]
    fn execution_phase_order() {
        assert!(ExecutionPhase::Initialization < ExecutionPhase::Input);
        assert!(ExecutionPhase::Input < ExecutionPhase::Simulation);
        assert!(ExecutionPhase::Simulation < ExecutionPhase::PostSimulation);
        assert!(ExecutionPhase::PostSimulation < ExecutionPhase::Cleanup);
    }

    #[test]
    fn execution_phase_roundtrip() {
        for i in 0u8..5 {
            let phase = ExecutionPhase::from_u8(i).unwrap();
            assert_eq!(phase.as_u8(), i);
        }
    }

    #[test]
    fn invalid_phase_returns_none() {
        assert!(ExecutionPhase::from_u8(99).is_none());
    }

    #[test]
    fn simulation_allows_gameplay_writes() {
        assert!(ExecutionPhase::Simulation.allows_gameplay_writes());
        assert!(!ExecutionPhase::Cleanup.allows_gameplay_writes());
        assert!(!ExecutionPhase::PostSimulation.allows_gameplay_writes());
    }

    #[test]
    fn system_version_display() {
        let v = SystemVersion::new(2, 3);
        assert_eq!(v.to_string(), "2.3");
    }

    #[test]
    fn depends_on_system_works() {
        let mut sys = SystemDefinition::new("sys_camera", "CameraSystem");
        sys.depends_on.push("sys_movement".into());
        assert!(sys.depends_on_system("sys_movement"));
        assert!(!sys.depends_on_system("sys_ai"));
    }
}
