"""
animation_contract.py — AnimationContract struct (Audit 2, Audit 3).

CLAUDE.md: "Animation Contract: auto-generated from COMP_ANIMATION_V2 —
tells engine exactly what states, parameters, IK, animation event timings
are needed. Lives in packages/asset-registry/."

## What the Animation Contract Does
When XACE sends a COMP_ANIMATION_V2 component to the engine adapter, the
engine needs to know:
  - What animation states must exist in the controller (per layer)
  - What animator parameters the runtime will set (BOOL/FLOAT/INT/TRIGGER)
  - What blend trees need x/y parameters
  - What IK configuration is required
  - What animation events XACE expects to fire at what normalized times

Without the contract, the engine adapter has to guess from the component
data alone — and mismatches (state names don't exist, parameters missing)
cause silent failures. With the contract, the engine adapter validates on
connection and reports mismatches as EngineError feedback.

## Relationship to COMP_ANIMATION_V2
COMP_ANIMATION_V2 is the runtime component — it carries playback state.
AnimationContract is the design-time specification — it declares what the
animation system must look like for a given entity archetype.

The contract is generated once per CGS version (when COMP_ANIMATION_V2
is first defined for an actor archetype) and cached. If COMP_ANIMATION_V2
changes, the contract is regenerated by animation_contract_generator.py.

## Serialization
AnimationContracts are serialized to JSON and sent as part of the
initial SnapshotPayload to the engine adapter. The engine validates
its loaded AnimationController asset against the contract and reports
mismatches as EngineError feedback.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


# ── Parameter Types ───────────────────────────────────────────────────────────

class AnimationParameterType(str, Enum):
    """
    Mirrors COMP_ANIMATION_V2 parameter types from CLAUDE.md.
    These are the types the Animator/AnimBlueprint parameter system supports.
    """
    BOOL    = "BOOL"
    FLOAT   = "FLOAT"
    INT     = "INT"
    TRIGGER = "TRIGGER"


# ── Blend Tree Types ──────────────────────────────────────────────────────────

class BlendType(str, Enum):
    """Blend tree interpolation type."""
    SIMPLE_DIRECTIONAL  = "SIMPLE_DIRECTIONAL"
    FREEFORM_DIRECTIONAL = "FREEFORM_DIRECTIONAL"
    FREEFORM_CARTESIAN  = "FREEFORM_CARTESIAN"
    DIRECT              = "DIRECT"


# ── Contract Sub-Structs ──────────────────────────────────────────────────────

@dataclass
class ContractLayer:
    """
    One animation layer definition.
    Declares the states that must exist and the default state.
    """
    layer_name: str
    default_state: str
    required_states: list[str] = field(default_factory=list)
    weight: float = 1.0
    mask: Optional[str] = None          # bone mask name, if any
    additive: bool = False

    def to_dict(self) -> dict:
        return {
            "layer_name": self.layer_name,
            "default_state": self.default_state,
            "required_states": sorted(self.required_states),  # D11
            "weight": self.weight,
            "mask": self.mask,
            "additive": self.additive,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "ContractLayer":
        return cls(
            layer_name=data["layer_name"],
            default_state=data["default_state"],
            required_states=data.get("required_states", []),
            weight=data.get("weight", 1.0),
            mask=data.get("mask"),
            additive=data.get("additive", False),
        )


@dataclass
class ContractParameter:
    """
    One animator parameter declaration.
    Declares type and default value — engine must expose this parameter.
    """
    name: str
    param_type: AnimationParameterType
    default_value: object = None   # bool/float/int/None depending on type

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "param_type": self.param_type.value,
            "default_value": self.default_value,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "ContractParameter":
        return cls(
            name=data["name"],
            param_type=AnimationParameterType(data["param_type"]),
            default_value=data.get("default_value"),
        )


@dataclass
class ContractBlendTree:
    """
    A 2D blend tree declaration (Audit 3 blend_parameters support).
    """
    tree_name: str
    x_parameter: str
    y_parameter: str
    blend_type: BlendType = BlendType.SIMPLE_DIRECTIONAL

    def to_dict(self) -> dict:
        return {
            "tree_name": self.tree_name,
            "x_parameter": self.x_parameter,
            "y_parameter": self.y_parameter,
            "blend_type": self.blend_type.value,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "ContractBlendTree":
        return cls(
            tree_name=data["tree_name"],
            x_parameter=data["x_parameter"],
            y_parameter=data["y_parameter"],
            blend_type=BlendType(data.get("blend_type", "SIMPLE_DIRECTIONAL")),
        )


@dataclass
class ContractAnimationEvent:
    """
    One animation event declaration (Audit 3 pending_events support).
    Declares when in the animation playback an event should fire.
    """
    event_id: str
    state_name: str
    layer_name: str
    trigger_at_normalized_time: float   # 0.0 = start, 1.0 = end
    game_event_type: str                # EventType string, e.g. "combat.hit_landed"

    def to_dict(self) -> dict:
        return {
            "event_id": self.event_id,
            "state_name": self.state_name,
            "layer_name": self.layer_name,
            "trigger_at_normalized_time": self.trigger_at_normalized_time,
            "game_event_type": self.game_event_type,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "ContractAnimationEvent":
        return cls(
            event_id=data["event_id"],
            state_name=data["state_name"],
            layer_name=data["layer_name"],
            trigger_at_normalized_time=data["trigger_at_normalized_time"],
            game_event_type=data["game_event_type"],
        )


@dataclass
class ContractIKConfig:
    """
    IK configuration declaration (Audit 3 COMP_IK_V1 support).
    Declares which IK features the engine must support for this actor.
    """
    ik_mode: str                        # Matches COMP_IK_V1.ik_mode values
    has_look_at: bool = False
    has_left_hand: bool = False
    has_right_hand: bool = False
    has_foot_placement: bool = False
    carry_ik_preset: Optional[str] = None   # e.g. "CARRY_OVER_SHOULDER"
    solve_order: str = "FABRIK"

    def to_dict(self) -> dict:
        return {
            "ik_mode": self.ik_mode,
            "has_look_at": self.has_look_at,
            "has_left_hand": self.has_left_hand,
            "has_right_hand": self.has_right_hand,
            "has_foot_placement": self.has_foot_placement,
            "carry_ik_preset": self.carry_ik_preset,
            "solve_order": self.solve_order,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "ContractIKConfig":
        return cls(
            ik_mode=data["ik_mode"],
            has_look_at=data.get("has_look_at", False),
            has_left_hand=data.get("has_left_hand", False),
            has_right_hand=data.get("has_right_hand", False),
            has_foot_placement=data.get("has_foot_placement", False),
            carry_ik_preset=data.get("carry_ik_preset"),
            solve_order=data.get("solve_order", "FABRIK"),
        )


# ── Animation Contract ────────────────────────────────────────────────────────

@dataclass
class AnimationContract:
    """
    The full animation specification for one actor archetype.

    Generated from COMP_ANIMATION_V2 by AnimationContractGenerator.
    Sent to the engine adapter as part of the initial SnapshotPayload.
    The engine validates its animation controller assets against this
    contract and reports mismatches as EngineError feedback.

    ## Versioning
    contract_version is incremented each time the contract is regenerated
    (i.e. each time COMP_ANIMATION_V2 is modified for this actor).
    The engine caches contracts by (actor_id, contract_version) and
    only re-validates when the version changes.
    """

    # Which actor archetype this contract belongs to
    actor_id: str

    # The asset_id of the animation controller this contract describes
    controller_asset_id: str

    # Contract version — incremented on regeneration
    contract_version: int = 1

    # CGS schema version when this contract was generated
    schema_version: str = "0.1.0"

    # Animation layers (base layer always present)
    layers: list[ContractLayer] = field(default_factory=list)

    # Animator parameters the runtime will set
    parameters: list[ContractParameter] = field(default_factory=list)

    # Blend trees
    blend_trees: list[ContractBlendTree] = field(default_factory=list)

    # Animation events that XACE expects to receive
    animation_events: list[ContractAnimationEvent] = field(default_factory=list)

    # IK configuration (None if entity has no IK component)
    ik_config: Optional[ContractIKConfig] = None

    # ── Convenience Accessors ──────────────────────────────────────────────

    @property
    def layer_names(self) -> list[str]:
        """Returns all layer names in declaration order."""
        return [l.layer_name for l in self.layers]

    @property
    def parameter_names(self) -> list[str]:
        """Returns all parameter names sorted (D11)."""
        return sorted(p.name for p in self.parameters)

    def get_layer(self, layer_name: str) -> Optional[ContractLayer]:
        """Returns the ContractLayer with the given name, or None."""
        return next((l for l in self.layers if l.layer_name == layer_name), None)

    def get_parameter(self, name: str) -> Optional[ContractParameter]:
        """Returns the ContractParameter with the given name, or None."""
        return next((p for p in self.parameters if p.name == name), None)

    def has_ik(self) -> bool:
        """True if this contract declares IK requirements."""
        return self.ik_config is not None

    def event_count(self) -> int:
        """Total number of animation events declared."""
        return len(self.animation_events)

    # ── Serialization ─────────────────────────────────────────────────────

    def to_dict(self) -> dict:
        return {
            "actor_id": self.actor_id,
            "controller_asset_id": self.controller_asset_id,
            "contract_version": self.contract_version,
            "schema_version": self.schema_version,
            "layers": [l.to_dict() for l in self.layers],
            "parameters": [p.to_dict() for p in self.parameters],
            "blend_trees": [b.to_dict() for b in self.blend_trees],
            "animation_events": [e.to_dict() for e in self.animation_events],
            "ik_config": self.ik_config.to_dict() if self.ik_config else None,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "AnimationContract":
        return cls(
            actor_id=data["actor_id"],
            controller_asset_id=data["controller_asset_id"],
            contract_version=data.get("contract_version", 1),
            schema_version=data.get("schema_version", "0.1.0"),
            layers=[ContractLayer.from_dict(l) for l in data.get("layers", [])],
            parameters=[ContractParameter.from_dict(p) for p in data.get("parameters", [])],
            blend_trees=[ContractBlendTree.from_dict(b) for b in data.get("blend_trees", [])],
            animation_events=[
                ContractAnimationEvent.from_dict(e)
                for e in data.get("animation_events", [])
            ],
            ik_config=(
                ContractIKConfig.from_dict(data["ik_config"])
                if data.get("ik_config") else None
            ),
        )

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str) -> "AnimationContract":
        return cls.from_dict(json.loads(json_str))

    def __repr__(self) -> str:
        return (
            f"AnimationContract("
            f"actor='{self.actor_id}', "
            f"layers={len(self.layers)}, "
            f"params={len(self.parameters)}, "
            f"events={self.event_count()}, "
            f"ik={self.has_ik()}, "
            f"v{self.contract_version})"
        )