"""
asset_report.py — Status report for the builder UI asset panel (Audit 2).

The AssetReport compiles a human-readable, structured summary of the
current asset registry state for the builder workspace UI (Phase 14).

## What the Builder UI Shows
CLAUDE.md Audit 2: "Asset status panel: placeholder count, link options,
game runs as grey boxes message"

The builder UI asset panel shows:
  - Overall summary bar: "7 assets are placeholders — game runs but looks like grey boxes"
  - Per-type breakdown: "Meshes: 3 linked, 2 placeholder | Audio: 1 linked, 1 missing"
  - Problem list: all UNRESOLVED (errors) and MISSING (warnings) refs
  - Quick-link suggestions: which placeholders are easiest to link

## Report Freshness
Reports are generated on demand, not cached. They take a snapshot of the
manifest at the moment of generation. The builder UI refreshes the report
after every schema mutation and after every engine feedback sync.

## Serialization
Reports serialize to JSON for the builder UI frontend (Phase 14 TypeScript).
The structure matches the props expected by the AssetStatusPanel component.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

from asset_manifest import AssetManifest, ManifestMetrics
from asset_reference import AssetReference
from asset_status_enum import AssetStatus
from asset_type_enum import AssetType
from placeholder_registry import PlaceholderRegistry


# ── Type Summary ──────────────────────────────────────────────────────────────

@dataclass
class AssetTypeSummary:
    """Status breakdown for one AssetType."""
    asset_type: AssetType
    total: int
    linked: int
    placeholder: int
    missing: int
    unresolved: int

    @property
    def is_fully_linked(self) -> bool:
        return self.linked == self.total and self.total > 0

    @property
    def has_problems(self) -> bool:
        return self.missing > 0 or self.unresolved > 0

    def to_dict(self) -> dict:
        return {
            "asset_type": self.asset_type.value,
            "total": self.total,
            "linked": self.linked,
            "placeholder": self.placeholder,
            "missing": self.missing,
            "unresolved": self.unresolved,
            "is_fully_linked": self.is_fully_linked,
            "has_problems": self.has_problems,
        }


# ── Problem Entry ─────────────────────────────────────────────────────────────

@dataclass
class AssetProblem:
    """One problem (error or warning) to surface in the builder UI."""
    asset_id: str
    asset_type: AssetType
    severity: str           # "error" | "warning"
    title: str
    description: str
    action_hint: str        # What the designer should do

    def to_dict(self) -> dict:
        return {
            "asset_id": self.asset_id,
            "asset_type": self.asset_type.value,
            "severity": self.severity,
            "title": self.title,
            "description": self.description,
            "action_hint": self.action_hint,
        }


# ── Placeholder Suggestion ────────────────────────────────────────────────────

@dataclass
class PlaceholderSuggestion:
    """
    A suggested asset to link, shown in the builder UI 'Link Assets' panel.
    Ranked by importance: MESH first (most visible), then AUDIO, then others.
    """
    asset_id: str
    asset_type: AssetType
    entity_id: Optional[str]
    display_name: str       # Human-readable, built from asset_id
    priority: int           # Lower = more important to link first

    def to_dict(self) -> dict:
        return {
            "asset_id": self.asset_id,
            "asset_type": self.asset_type.value,
            "entity_id": self.entity_id,
            "display_name": self.display_name,
            "priority": self.priority,
        }


# ── Asset Report ──────────────────────────────────────────────────────────────

@dataclass
class AssetReport:
    """
    Full asset status report for the builder UI.

    Generated by AssetReportGenerator.generate() on demand.
    Serialized to JSON for the Phase 14 TypeScript frontend.
    """
    generated_at: datetime
    schema_version: str

    # Top-level summary for the status bar
    summary_bar: str                    # "7 assets are placeholders..."
    total_refs: int
    linked_count: int
    placeholder_count: int
    missing_count: int
    unresolved_count: int

    # Per-type breakdowns (only types with refs included)
    type_summaries: list[AssetTypeSummary]

    # Problems to show in the warning/error panel
    problems: list[AssetProblem]

    # Placeholder link suggestions (top N, ranked by priority)
    suggestions: list[PlaceholderSuggestion]

    # Whether the registry currently blocks CGS commit
    blocks_commit: bool

    @property
    def error_count(self) -> int:
        return sum(1 for p in self.problems if p.severity == "error")

    @property
    def warning_count(self) -> int:
        return sum(1 for p in self.problems if p.severity == "warning")

    @property
    def is_clean(self) -> bool:
        """True if no problems at all."""
        return not self.problems

    def to_dict(self) -> dict:
        return {
            "generated_at": self.generated_at.isoformat(),
            "schema_version": self.schema_version,
            "summary_bar": self.summary_bar,
            "total_refs": self.total_refs,
            "linked_count": self.linked_count,
            "placeholder_count": self.placeholder_count,
            "missing_count": self.missing_count,
            "unresolved_count": self.unresolved_count,
            "blocks_commit": self.blocks_commit,
            "error_count": self.error_count,
            "warning_count": self.warning_count,
            "type_summaries": [t.to_dict() for t in self.type_summaries],
            "problems": [p.to_dict() for p in self.problems],
            "suggestions": [s.to_dict() for s in self.suggestions],
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent, default=str)


# ── Asset Report Generator ────────────────────────────────────────────────────

# Priority order for placeholder suggestions — most visible / impactful first
_SUGGESTION_PRIORITY: dict[AssetType, int] = {
    AssetType.MESH:                 1,
    AssetType.ANIMATION_CONTROLLER: 2,
    AssetType.MATERIAL:             3,
    AssetType.TEXTURE:              4,
    AssetType.AUDIO_CLIP:           5,
    AssetType.AUDIO_MUSIC:          6,
    AssetType.SPRITE:               7,
    AssetType.PARTICLE:             8,
    AssetType.PREFAB:               9,
    AssetType.FONT:                 10,
}

_MAX_SUGGESTIONS = 20   # Cap for the builder UI suggestion list


class AssetReportGenerator:
    """
    Generates AssetReport snapshots from the current manifest state.

    Stateless — create once and call generate() repeatedly.
    """

    def __init__(
        self,
        manifest: AssetManifest,
        placeholder_registry: PlaceholderRegistry,
        schema_version: str = "0.1.0",
    ) -> None:
        self._manifest = manifest
        self._placeholder_registry = placeholder_registry
        self._schema_version = schema_version

    # ── Primary API ───────────────────────────────────────────────────────

    def generate(self) -> AssetReport:
        """
        Generates a full AssetReport from the current manifest state.
        Called after every schema mutation and every engine feedback sync.
        """
        metrics = self._manifest.compute_metrics()

        return AssetReport(
            generated_at=datetime.utcnow(),
            schema_version=self._schema_version,
            summary_bar=self._build_summary_bar(metrics),
            total_refs=metrics.total_references,
            linked_count=metrics.linked_count,
            placeholder_count=metrics.placeholder_count,
            missing_count=metrics.missing_count,
            unresolved_count=metrics.unresolved_count,
            type_summaries=self._build_type_summaries(),
            problems=self._build_problems(),
            suggestions=self._build_suggestions(),
            blocks_commit=metrics.has_blockers,
        )

    def generate_minimal(self) -> dict:
        """
        Generates a lightweight summary dict for the status bar only.
        Used for high-frequency UI refreshes where the full report is too expensive.
        """
        metrics = self._manifest.compute_metrics()
        return {
            "summary_bar": self._build_summary_bar(metrics),
            "blocks_commit": metrics.has_blockers,
            "placeholder_count": metrics.placeholder_count,
            "missing_count": metrics.missing_count,
            "unresolved_count": metrics.unresolved_count,
            "linked_count": metrics.linked_count,
        }

    # ── Internal Builders ─────────────────────────────────────────────────

    def _build_summary_bar(self, metrics: ManifestMetrics) -> str:
        """
        Builds the top-level summary bar message.
        Matches the CLAUDE.md Audit 2 zero-experience wording exactly.
        """
        return metrics.builder_summary

    def _build_type_summaries(self) -> list[AssetTypeSummary]:
        """Builds per-type status breakdowns for types with at least one ref."""
        summaries = []
        for asset_type in AssetType:
            refs = self._manifest.get_by_type(asset_type)
            if not refs:
                continue

            linked      = sum(1 for r in refs if r.status == AssetStatus.LINKED)
            placeholder = sum(1 for r in refs if r.status == AssetStatus.PLACEHOLDER)
            missing     = sum(1 for r in refs if r.status == AssetStatus.MISSING)
            unresolved  = sum(1 for r in refs if r.status == AssetStatus.UNRESOLVED)

            summaries.append(AssetTypeSummary(
                asset_type=asset_type,
                total=len(refs),
                linked=linked,
                placeholder=placeholder,
                missing=missing,
                unresolved=unresolved,
            ))

        return summaries

    def _build_problems(self) -> list[AssetProblem]:
        """
        Builds the problem list — UNRESOLVED errors first, then MISSING warnings.
        Sorted within each severity by asset_id (D11).
        """
        problems: list[AssetProblem] = []

        # Errors first — UNRESOLVED blocks commit (I12)
        for ref in self._manifest.get_all_unresolved():
            problems.append(AssetProblem(
                asset_id=ref.asset_id,
                asset_type=ref.asset_type,
                severity="error",
                title="Unresolved Asset Reference",
                description=(
                    f"'{ref.asset_id}' exists in your game design but was never "
                    "registered in the Asset Registry. This blocks saving."
                ),
                action_hint=(
                    "This is a registration bug. Check which system created "
                    "this reference without going through the auto-registration flow."
                ),
            ))

        # Then warnings — MISSING does not block commit
        for ref in self._manifest.get_all_missing():
            problems.append(AssetProblem(
                asset_id=ref.asset_id,
                asset_type=ref.asset_type,
                severity="warning",
                title="Asset File Not Found",
                description=(
                    f"'{ref.asset_id}' was previously linked but the file "
                    "can no longer be found. The engine will render a grey box."
                ),
                action_hint=(
                    "Re-link the asset to a new file, or the engine will "
                    "fall back to placeholder rendering."
                ),
            ))

        return problems

    def _build_suggestions(self) -> list[PlaceholderSuggestion]:
        """
        Builds the top-N placeholder link suggestions, ranked by asset type priority.
        MESHes are most visible so they rank first.
        """
        entries = self._placeholder_registry.get_all()

        suggestions = []
        for entry in entries:
            display = (
                entry.asset_id
                .replace("_", " ")
                .replace(" v1", " (v1)")
                .title()
            )
            suggestions.append(PlaceholderSuggestion(
                asset_id=entry.asset_id,
                asset_type=entry.asset_type,
                entity_id=entry.entity_id,
                display_name=display,
                priority=_SUGGESTION_PRIORITY.get(entry.asset_type, 99),
            ))

        # Sort: priority ASC (lower = more important), then asset_id ASC (D11)
        suggestions.sort(key=lambda s: (s.priority, s.asset_id))
        return suggestions[:_MAX_SUGGESTIONS]