//! # Entity ID Generator
//!
//! Monotonic 64-bit ID generator for the EntityStore.
//! Never reuses IDs. Never generates NULL_ENTITY_ID (0).
//! Thread-safe via AtomicU64 for parallel system execution.
//!
//! ## Determinism (D2)
//! EntityIDs are never reused after destruction. This generator
//! only increments — it never decrements or wraps. The counter
//! can be restored from a snapshot to ensure IDs generated after
//! restore never collide with IDs that existed before the snapshot.
//!
//! ## Relationship to xace_core::entity_id::EntityIdGenerator
//! The core package defines the EntityIdGenerator type as a public API.
//! This module is the runtime-core's internal instance of that generator,
//! used exclusively by the EntityStore. It wraps the core type with
//! runtime-specific behavior and documentation.

use std::sync::atomic::{AtomicU64, Ordering};
use xace_core::entity_id::{EntityID, NULL_ENTITY_ID};

// ── Entity ID Generator ───────────────────────────────────────────────────────

/// Monotonic EntityID generator for the runtime EntityStore.
///
/// Produces unique, strictly increasing EntityIDs.
/// Counter starts at 1 — NULL_ENTITY_ID (0) is permanently skipped.
/// Thread-safe via AtomicU64 with Relaxed ordering — correctness
/// is guaranteed by the atomic increment itself, not by memory
/// visibility ordering between threads.
///
/// ## Snapshot Restore
/// `restore_to(value)` resets the counter to a specific value.
/// Called by the EntityStore during snapshot restore to ensure
/// newly generated IDs never collide with pre-snapshot IDs.
/// The restore value must always be greater than any EntityID
/// currently in the EntityStore — enforced by the SnapshotEngine.
pub struct EntityIdGenerator {
    /// Atomic counter. Starts at 1. Increments monotonically.
    /// Never returns to 0 or wraps (u64 max ≈ 1.8 × 10¹⁹).
    counter: AtomicU64,
}

impl EntityIdGenerator {
    /// Creates a new generator. Counter starts at 1.
    /// NULL_ENTITY_ID (0) is permanently skipped.
    pub fn new() -> Self {
        Self {
            counter: AtomicU64::new(1),
        }
    }

    /// Generates the next unique EntityID.
    ///
    /// Atomically increments and returns the pre-increment value.
    /// Safe to call from multiple threads simultaneously.
    ///
    /// ## Guarantees
    /// - Return value is always > 0 (never NULL_ENTITY_ID)
    /// - Return value is unique across all calls on this instance
    /// - Return values are strictly increasing
    pub fn next_id(&self) -> EntityID {
        let id = self.counter.fetch_add(1, Ordering::Relaxed);
        // Defensive check — should never happen with u64 range
        debug_assert_ne!(
            id, NULL_ENTITY_ID,
            "EntityIdGenerator wrapped to 0 — u64 overflow"
        );
        id
    }

    /// Returns the next ID that would be generated without consuming it.
    ///
    /// Used by EntityStore.peek_next_id() for snapshot serialization.
    /// Does not advance the counter.
    pub fn peek_next(&self) -> EntityID {
        self.counter.load(Ordering::Relaxed)
    }

    /// Restores the generator counter to a specific value.
    ///
    /// Called exclusively by EntityStore.restore_from_snapshot()
    /// after snapshot restore. Ensures newly generated IDs never
    /// collide with IDs that existed before the snapshot tick.
    ///
    /// ## Contract
    /// `value` must be greater than any EntityID currently in the
    /// EntityStore. This is enforced by the SnapshotEngine, not here.
    ///
    /// ## Why Relaxed Ordering
    /// The restore happens during snapshot restore — a single-threaded
    /// operation where no other systems are running. Relaxed ordering
    /// is safe here because there is no concurrent access at this point.
    pub fn restore_to(&self, value: EntityID) {
        debug_assert!(
            value > NULL_ENTITY_ID,
            "Cannot restore EntityIdGenerator to NULL_ENTITY_ID"
        );
        self.counter.store(value, Ordering::Relaxed);
    }

    /// Returns the current counter value.
    /// Equivalent to peek_next() — alias for clarity in some contexts.
    pub fn current_value(&self) -> EntityID {
        self.counter.load(Ordering::Relaxed)
    }

    /// Returns true if the given ID was generated by this instance.
    ///
    /// An ID was generated if it is > 0 and < current counter value.
    /// Used for debugging and validation only.
    pub fn was_generated(&self, id: EntityID) -> bool {
        id > NULL_ENTITY_ID && id < self.counter.load(Ordering::Relaxed)
    }
}

impl Default for EntityIdGenerator {
    fn default() -> Self {
        Self::new()
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn first_id_is_never_null() {
        let gen = EntityIdGenerator::new();
        assert_ne!(gen.next_id(), NULL_ENTITY_ID);
    }

    #[test]
    fn first_id_is_one() {
        let gen = EntityIdGenerator::new();
        assert_eq!(gen.next_id(), 1);
    }

    #[test]
    fn ids_are_monotonically_increasing() {
        let gen = EntityIdGenerator::new();
        let a = gen.next_id();
        let b = gen.next_id();
        let c = gen.next_id();
        assert!(a < b && b < c);
    }

    #[test]
    fn ids_are_sequential() {
        let gen = EntityIdGenerator::new();
        for expected in 1u64..=10 {
            assert_eq!(gen.next_id(), expected);
        }
    }

    #[test]
    fn peek_does_not_advance_counter() {
        let gen = EntityIdGenerator::new();
        let peeked = gen.peek_next();
        let generated = gen.next_id();
        assert_eq!(peeked, generated);
    }

    #[test]
    fn peek_reflects_next_id() {
        let gen = EntityIdGenerator::new();
        gen.next_id(); // consume 1
        gen.next_id(); // consume 2
        assert_eq!(gen.peek_next(), 3);
    }

    #[test]
    fn restore_sets_counter_correctly() {
        let gen = EntityIdGenerator::new();
        gen.next_id();
        gen.next_id();
        gen.restore_to(1000);
        assert_eq!(gen.next_id(), 1000);
        assert_eq!(gen.next_id(), 1001);
    }

    #[test]
    fn restore_prevents_id_collision() {
        let gen = EntityIdGenerator::new();
        // Simulate: IDs 1-5 were generated before snapshot
        for _ in 0..5 { gen.next_id(); }
        // Restore ensures next ID is beyond previous range
        gen.restore_to(6);
        let new_id = gen.next_id();
        assert!(new_id >= 6, "Restored ID should not collide with pre-snapshot IDs");
    }

    #[test]
    fn was_generated_correct() {
        let gen = EntityIdGenerator::new();
        let id = gen.next_id();
        assert!(gen.was_generated(id));
        assert!(!gen.was_generated(NULL_ENTITY_ID));
        assert!(!gen.was_generated(gen.peek_next())); // not yet generated
    }

    #[test]
    fn current_value_matches_peek() {
        let gen = EntityIdGenerator::new();
        gen.next_id();
        gen.next_id();
        assert_eq!(gen.current_value(), gen.peek_next());
    }

    #[test]
    fn thread_safe_concurrent_generation() {
        use std::sync::Arc;
        use std::thread;
        use std::collections::HashSet;

        let gen = Arc::new(EntityIdGenerator::new());
        let thread_count = 8;
        let ids_per_thread = 100;

        let handles: Vec<_> = (0..thread_count).map(|_| {
            let gen_clone = Arc::clone(&gen);
            thread::spawn(move || {
                (0..ids_per_thread)
                    .map(|_| gen_clone.next_id())
                    .collect::<Vec<_>>()
            })
        }).collect();

        let mut all_ids: HashSet<EntityID> = HashSet::new();
        for handle in handles {
            let ids = handle.join().unwrap();
            for id in ids {
                assert!(
                    all_ids.insert(id),
                    "Duplicate ID {} generated under concurrent access",
                    id
                );
            }
        }

        assert_eq!(
            all_ids.len(),
            thread_count * ids_per_thread,
            "All IDs must be unique"
        );
    }
}